In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5]


In [2]:
import numpy as np

# array with index
arr = np.array([
    [-1,  2,  0,  4],
    [ 4, -5,  6,  0],
    [ 1,  2,  3,  4]
])

# first 2 rows and alternate columns
arr2 = arr[:2, ::2]
print("first 2 rows and alternate columns")
print(arr2)

# elements at specific indices
arr3 = arr[[1, 1, 0, 2], [1, 2, 3, 3]]
print("\nElements at indices (1,1), (1,2), (0,3), (2,3):", arr3)


first 2 rows and alternate columns
[[-1  0]
 [ 4  6]]

Elements at indices (1,1), (1,2), (0,3), (2,3): [-5  6  4  4]


In [ ]:
a = np.array([[1,2], [3,4], [5,6]])

b = np.array([[7,8], [9,10], [11,12]])

print("Adding 1 to every element:",a+1)

print("\nSubtracting 1 from every element:",a-1)
print("\nElement-wise addition of two arrays:",a+b)
print("\nElement-wise multiplication of two arrays:",a*b)
print("\nElement-wise division of two arrays:",a/b)



Adding 1 to every element: [[2 3]
 [4 5]
 [6 7]]

Subtracting 1 from every element: [[0 1]
 [2 3]
 [4 5]]

Element-wise addition of two arrays: [[ 8 10]
 [12 14]
 [16 18]]

Element-wise multiplication of two arrays: [[ 7 16]
 [27 40]
 [55 72]]

Element-wise division of two arrays: [[0.14285714 0.25      ]
 [0.33333333 0.4       ]
 [0.45454545 0.5       ]]


In [10]:
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0,2.0])
print(x.dtype)

x = np.array([1,2],dtype=np.int64)
print(x.dtype)


int64
float64
int64


In [16]:
# import numpy as np
print(np.arange(1,10))
print(np.linspace(1,10,5))
print(np.zeros((3,4)))
print(np.ones((2,3,4),dtype=np.int16))
print(np.random.rand(5))

print(np.random.randint(5,size=10))


[1 2 3 4 5 6 7 8 9]
[ 1.    3.25  5.5   7.75 10.  ]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[0.59273349 0.94840716 0.95946603 0.32892239 0.13673268]
[2 3 1 0 4 0 2 2 0 4]


In [ ]:
print(np.zeros([4,3],dtype=np.int32)) # 4-rows and 3-columns
print(np.ones([4,3],dtype = np.int32))

print(np.full([2,2],67,dtype=int))
print(np.eye(4))

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[67 67]
 [67 67]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [22]:
arr = np.asarray([1,2,3,4,5])
print(arr.size)
print(arr.shape)
print(len(arr))
print(arr.dtype)
print(arr.ndim)

# arr = arr.astype('')

5
(5,)
5
int64
1


In [25]:
# change dtype to float
arr = arr.astype('float64')
print(arr.dtype)
print("Datatype:",arr.dtype)

lis = arr.tolist()
print(lis)

float64
Datatype: float64
[1.0, 2.0, 3.0, 4.0, 5.0]


In [27]:
a = np.array([1,4,9,16,25])

print(np.sqrt(a))
print(np.log(a))
print(np.exp(a))


[1. 2. 3. 4. 5.]
[0.         1.38629436 2.19722458 2.77258872 3.21887582]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [28]:
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(np.max(a))
print(np.mean(a))

[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
[ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]
25
11.0


In [30]:
a = np.array([1,4,9,16,25])
b = np.array([2,3,4,5,6])

print(a+b)
print(a @ b) #-> matrix multiplication
print(np.dot(a,b))

[ 3  7 13 21 31]
280
280
