In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5]


In [2]:
import numpy as np

# array with index
arr = np.array([
    [-1,  2,  0,  4],
    [ 4, -5,  6,  0],
    [ 1,  2,  3,  4]
])

# first 2 rows and alternate columns
arr2 = arr[:2, ::2]
print("first 2 rows and alternate columns")
print(arr2)

# elements at specific indices
arr3 = arr[[1, 1, 0, 2], [1, 2, 3, 3]]
print("\nElements at indices (1,1), (1,2), (0,3), (2,3):", arr3)


first 2 rows and alternate columns
[[-1  0]
 [ 4  6]]

Elements at indices (1,1), (1,2), (0,3), (2,3): [-5  6  4  4]
